[package]
name = "audio_transformers"
version = "0.1.0"
authors = ["Robinson Labourdette <robinson@inoft.com>"]
edition = "2018"

[lib]
name = "audio_transformers"
crate-type = ["lib"]

[dependencies]
hound = { version = "3.4.0" }


