root_file: __init__.py
package_type: "code"
python_path_exclusions:
  excluded_folders_names: ["dist", "build"]
global_exclusions:
  excluded_folders_names: ["venv/lib/site-packages"]
folders_includes:
  audio_engine/libs:
    additional_linux:
      excluded_files_extensions: [".pyd"]
    additional_windows:
      excluded_folders_names: ["audio_engine/libs"]
      excluded_files_extensions: [".so"]

