from typing import Union

FORMAT_TYPE_WAV = 'wav'
FORMAT_TYPE_MP3 = 'mp3'
OUT_FORMATS_UNION = Union[FORMAT_TYPE_WAV, FORMAT_TYPE_MP3]
EXPORT_TARGET_MANAGED_ENGINE = 'managed-inoft-vocal-engine'
EXPORT_TARGET_LOCAL = 'local'
EXPORT_TARGETS_UNION = Union[EXPORT_TARGET_MANAGED_ENGINE, EXPORT_TARGET_LOCAL]
